apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-mgr
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      replicas: 4
      resources:
        limits:
          memory: "2G"  # Maximum memory allowed
          cpu: "1000m"       # Maximum CPU allowed
        requests:
          memory: "1G"  # Requested Memory
          cpu: "100m"       # Requested CPU
      containers:
        — name: emp-mgr
        image: emp-mgr:latest
        ports:
        — containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 25
          periodSeconds: 5